name: backdriveb2
version: 0.1.12
base: core18

summary: Cross-platform user-friendly client for BackBlaze B2 storage
description: |
  BackDrive B2 is a cross-platform user-friendly client for BackBlaze B2 storage.

confinement: devmode
grade: stable

architectures:
  - build-on: amd64

parts:
  backdriveb2:
    plugin: python
    source: https://github.com/Joffreybvn/backdriveb2.git

  launcher:
    plugin: nil
    source: https://github.com/Joffreybvn/backdriveb2.git
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av start.sh $SNAPCRAFT_PART_INSTALL/bin/

apps:
  backdriveb2:
    command: bin/start.sh